name: Tagging

env:
  GH_TOKEN: ${{ github.token }}
  CURRENT_BRANCH: ${{ github.ref_name }}

on:
  push:
    branches:
      - dev

jobs:
  tag-colors-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${CURRENT_BRANCH} && cd ui && yarn tag:package -b ${CURRENT_BRANCH} -s -blui-colors

  tag-branding-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd branding && yarn tag:package -b ${CURRENT_BRANCH} -s -blui-colors-branding
